### ISSUE TITLE
Binary logging config not taking on first run

### ISSUE THREAD

**Issue by wyaeld** [Oefenweb/ansible-percona-server#24]
with a vars section like this

``` yml
    percona_server_etc_my_cnf:
      - section: mysqld
        options:
          - name: socket
            value: /var/run/mysqld/mysqld.sock
          - name: server_id
            value: "{{ hostvars[inventory_hostname]['mysql_server_id'] }}"
          - name: log_bin
            value: mysql-bin
          - name: log_bin_index
            value: mysql-bin.index
          - name: report_host
            value: "{{ inventory_hostname }}"
```

seeing any issue where the database is running, but doesn't think binary logging is

```
mysql> show binary logs;
ERROR 1381 (HY000): You are not using binary logging
```

however if I reboot the system, it comes back up with binary logging working.  I've looked at the tasks, but not clear to me why the restarts would do it, unless restart is insufficient to reload config
